apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: snort-agent
  name: snort-agent
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: snort-agent
  template:
    metadata:
      labels:
        app: snort-agent
    spec:
      containers:
      - name: snort-agent
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        resources:
          limits:
            memory: 1Gi
        ports:
          #- name: snort-port
          
        #Logica para extraer todos los puertos 
        {{- $portList := list -}}
        {{- range $interface := .Values.service.interfaces }}
        {{- range $port := index $.Values.service $interface "ports" }}
        {{- if not (has $port $portList) }}
          {{- $portList = append $portList . }}
        {{- end }}
        {{- end }}
        {{- end }}
          {{- range $port := $portList }}
          - containerPort: {{ $port }}
          {{- end }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}