{{- range $interface := .Values.service.interfaces }}
apiVersion: v1
kind: Service
metadata:
  name: snort-svc-{{ $interface }}
  annotations:
    {{- if ne $interface "Default" }}
    metallb.universe.tf/address-pool: {{ $interface }}
    {{- end }}
  labels:
    app: snort-svc-{{ $interface }}
spec:
  type: {{ index $.Values.service $interface "type" }}
  {{- if index $.Values.service $interface "ip" }}
  loadBalancerIP: {{ index $.Values.service $interface "ip" }}
  {{- end }}  
  selector:
    app: snort-agent
  ports: 
    #- name: snort-port
    {{- range $port := index $.Values.service $interface "ports" }}
    - port: {{ $port }}
    {{- end }}
---
{{- end }}