# Default values for snort.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: docker-registry.ants.k8s.gaialab:80/snort-agent
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "1.0"

resource:
  request:
    memory: "500Mi"
    cpu: "256m"
  limit:
    memory: "1Gi"
    cpu: "500m"

service:
  interfaces: [public-pool, virtual-pool-1, virtual-pool-2]
  public-pool:
    type: LoadBalancer
    ports: [8011]
  virtual-pool-1:
    type: LoadBalancer
    ports: [8011]
  virtual-pool-2:
    type: LoadBalancer
    ports: [8011]
